# ml-service/docker-compose.yml
version: '3.8'
services:
  ml-humanization-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache
    volumes:
      - ./.cache:/app/.cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped