version: '3.8'
services:
  nextjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - NODE_ENV=production
    depends_on:
      - ml-service
    networks:
      - app-network

  ml-service:
    build: 
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache
    volumes:
      - ml-cache:/app/.cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - app-network

volumes:
  ml-cache:

networks:
  app-network:
    driver: bridge