services:
  # The Next.js Frontend Service
  - type: web
    name: lab-report-ai
    env: docker
    repo: https://github.com/AmitRiya14/lab-report-ai
    dockerContext: .
    dockerfilePath: ./Dockerfile
    domains:
      - gradelylabs.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: ML_SERVICE_URL
        value: http://ml-service:8000
      - key: NEXTAUTH_URL
        value: https://gradelylabs.com

  # The Python ML Backend Service
  - type: web
    name: ml-service
    env: docker
    repo: https://github.com/AmitRiya14/lab-report-ai
    dockerContext: ./ml-service
    dockerfilePath: ./ml-service/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /app/.cache # This path matches the disk's mountPath

# Top-level definition for all persistent disks in this Blueprint
disks:
  - name: ml-cache
    mountPath: /app/.cache
    sizeGB: 10