name: ML Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'ml-service/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'ml-service/**' ]

jobs:
  test-ml-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('ml-service/requirements.txt') }}
        
    - name: Install dependencies
      run: |
        cd ml-service
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
        
    - name: Run tests
      run: |
        cd ml-service
        python -m pytest tests/ -v --cov=. --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./ml-service/coverage.xml
        
  build-and-push:
    needs: test-ml-service
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and push Docker image
      run: |
        cd ml-service
        docker build -t ml-humanization:latest .
        # Add your registry push commands here